create table if not exists public.edc_fleet_quote_profiles (
  id uuid primary key default gen_random_uuid(),
  public_token uuid not null default gen_random_uuid(),
  customer_name text not null,
  customer_phone_last4 text not null,
  passcode_hash text not null,
  province text not null default 'ON',
  apr numeric not null default 0.0799,
  term_months integer not null default 96,
  warranty_tier text not null default '3yr',
  max_selling_price numeric,
  max_monthly_payment numeric,
  max_biweekly_payment numeric,
  hide_disqualified boolean not null default false,
  suggested_vehicle_ids text[] not null default '{}'::text[],
  selected_vehicle_ids text[] not null default '{}'::text[],
  staff_note text,
  unlocked_at timestamptz,
  view_expires_at timestamptz,
  submitted_at timestamptz,
  expires_at timestamptz not null default (now() + interval '24 hours'),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.edc_fleet_quote_profiles
  add column if not exists customer_phone_last4 text not null default '',
  add column if not exists passcode_hash text not null default '',
  add column if not exists province text not null default 'ON',
  add column if not exists apr numeric not null default 0.0799,
  add column if not exists term_months integer not null default 96,
  add column if not exists warranty_tier text not null default '3yr',
  add column if not exists max_selling_price numeric,
  add column if not exists max_monthly_payment numeric,
  add column if not exists max_biweekly_payment numeric,
  add column if not exists hide_disqualified boolean not null default false,
  add column if not exists suggested_vehicle_ids text[] not null default '{}'::text[],
  add column if not exists selected_vehicle_ids text[] not null default '{}'::text[],
  add column if not exists staff_note text,
  add column if not exists unlocked_at timestamptz,
  add column if not exists view_expires_at timestamptz,
  add column if not exists submitted_at timestamptz,
  add column if not exists expires_at timestamptz not null default (now() + interval '24 hours');

create unique index if not exists edc_fleet_quote_profiles_public_token_idx
  on public.edc_fleet_quote_profiles (public_token);

create index if not exists edc_fleet_quote_profiles_created_at_idx
  on public.edc_fleet_quote_profiles (created_at desc);

create index if not exists edc_fleet_quote_profiles_submitted_at_idx
  on public.edc_fleet_quote_profiles (submitted_at desc)
  where submitted_at is not null;

comment on table public.edc_fleet_quote_profiles is
  'Fleet finance quote links generated by staff for customer vehicle shortlist review.';

comment on column public.edc_fleet_quote_profiles.public_token is
  'Opaque public quote token used in customer-safe fleet quote URLs.';

comment on column public.edc_fleet_quote_profiles.passcode_hash is
  'Server-generated hash for the customer phone last-four passcode.';

comment on column public.edc_fleet_quote_profiles.suggested_vehicle_ids is
  'Staff-suggested fleet vehicle IDs shown first in the customer quote.';

comment on column public.edc_fleet_quote_profiles.selected_vehicle_ids is
  'Customer-selected top fleet vehicle IDs submitted from the public quote page.';
