alter table public.users
  add column if not exists access_all_deals boolean default false,
  add column if not exists access_all_leads_customers boolean default false,
  add column if not exists administrator boolean default false,
  add column if not exists approver boolean default false,
  add column if not exists vendors boolean default false,
  add column if not exists delete_vendors boolean default false,
  add column if not exists costs boolean default false,
  add column if not exists customers boolean default false,
  add column if not exists delete_customers boolean default false,
  add column if not exists sales boolean default false,
  add column if not exists delete_sales boolean default false,
  add column if not exists inventory boolean default false,
  add column if not exists delete_inventory boolean default false,
  add column if not exists settings boolean default false,
  add column if not exists sales_reports_access boolean default false,
  add column if not exists inventory_reports_access boolean default false;
