import test from 'node:test'
import assert from 'node:assert/strict'
import { readFile } from 'node:fs/promises'

test('facebook assistant installer starts from the Windows Startup folder without Task Scheduler', async () => {
  const source = await readFile(new URL('./install-facebook-assistant-startup.ps1', import.meta.url), 'utf8')

  assert.match(source, /Startup\\EasyDrive Facebook Assistant\.cmd/)
  assert.match(source, /EasyDrive Facebook Assistant/)
  assert.match(source, /facebook-marketplace-assist-runner\.mjs/)
  assert.match(source, /--profile-dir/)
  assert.match(source, /\.facebook-assist-profile/)
  assert.match(source, /\[int\]\$Port\s+=\s+4777/)
  assert.match(source, /--port\s+\$Port/)
  assert.match(source, /Stop-FacebookAssistantOnPort/)
  assert.match(source, /netstat -ano/)
  assert.match(source, /Stop-Process\s+-Id/)
  assert.match(source, /Start-Process\s+powershell\.exe/)
  assert.match(source, /WindowStyle\s+Hidden/)
  assert.doesNotMatch(source, /Register-ScheduledTask/)
  assert.doesNotMatch(source, /Start-ScheduledTask/)
  assert.doesNotMatch(source, /LeastPrivilege/)
  assert.doesNotMatch(source, /CodeGeneration/)
})

test('site-hosted facebook assistant package can install without the repo checkout', async () => {
  const installer = await readFile(new URL('../client/public/downloads/facebook-assistant/install.ps1', import.meta.url), 'utf8')
  const commandLauncher = await readFile(new URL('../client/public/downloads/facebook-assistant/install-facebook-assistant.cmd', import.meta.url), 'utf8')
  const pkg = JSON.parse(await readFile(new URL('../client/public/downloads/facebook-assistant/package.json', import.meta.url), 'utf8'))
  const publicRunner = await readFile(new URL('../client/public/downloads/facebook-assistant/facebook-marketplace-assist-runner.mjs', import.meta.url), 'utf8')
  const repoRunner = await readFile(new URL('./facebook-marketplace-assist-runner.mjs', import.meta.url), 'utf8')

  assert.match(installer, /https:\/\/easydrivecanada\.com/)
  assert.match(installer, /Invoke-WebRequest/)
  assert.match(installer, /npm\s+install\s+--omit=dev/)
  assert.match(installer, /start-facebook-assistant\.ps1/)
  assert.match(installer, /Startup\\EasyDrive Facebook Assistant\.cmd/)
  assert.match(installer, /Stop-FacebookAssistantOnPort/)
  assert.match(installer, /netstat -ano/)
  assert.match(installer, /Stop-Process\s+-Id/)
  assert.match(installer, /Start-Process\s+powershell\.exe/)
  assert.match(installer, /WindowStyle\s+Hidden/)
  assert.doesNotMatch(installer, /Register-ScheduledTask/)
  assert.doesNotMatch(installer, /Start-ScheduledTask/)
  assert.doesNotMatch(installer, /LeastPrivilege/)
  assert.doesNotMatch(installer, /RepoRoot/)
  assert.match(commandLauncher, /install\.ps1/)
  assert.match(commandLauncher, /ExecutionPolicy Bypass/)
  assert.match(commandLauncher, /-NoExit/)
  assert.match(commandLauncher, /https:\/\/easydrivecanada\.com\/downloads\/facebook-assistant\/install\.ps1/)
  assert.equal(pkg.scripts.start, 'node facebook-marketplace-assist-runner.mjs --port 4777 --profile-dir ".facebook-assist-profile"')
  assert.equal(pkg.dependencies.playwright, '^1.49.1')
  assert.equal(publicRunner, repoRunner)
})
